FROM nvidia/cuda:12.3.2-devel-ubuntu22.04

# Set the working directory in the container
WORKDIR /tuning_app

# Volumes for training logs and final model weights
VOLUME /tuning_app/

# Install any needed packages specified in requirements.txt
RUN apt-get update -y && apt-get upgrade -y && apt install --no-install-recommends -y build-essential python3 python3-pip && apt-get install -y git
RUN pip3 install argparse boto3 ruamel.yaml torch==2.2.0
RUN git clone https://github.com/OpenAccess-AI-Collective/axolotl /axolotl
RUN pip3 install packaging

# Change directory to /axolotl and install dependencies
RUN cd /axolotl && pip3 install -e '.[flash-attn,deepspeed]'
RUN cd /axolotl && pip3 install -e '.'

# Copy the current directory contents into the container at /tuning_app
COPY . /tuning_app/

# Create a script to run the last two commands
RUN mkdir -p /training_sh/
RUN echo '#!/bin/bash\npython3 yml_creator.py ./prompt_dir/prompt.json\npython3 -m axolotl.cli.train ./new_yaml.yml\npython3 s3_uploader.py ./ $BUCKET_NAME $NEW_DIR_NAME --access_key_id $ACCESS_KEY_ID --secret_access_key $SECRET_ACCESS_KEY' > /training_sh/run_commands.sh
RUN chmod +x /training_sh/run_commands.sh

# Set the entrypoint to the script
ENTRYPOINT ["/training_sh/run_commands.sh"]

