FROM ubuntu

# Set the working directory in the container
WORKDIR /rag_system

# Update and install python
sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get install -y python3-pip

# Copy the current directory contents into the container at /rag_system
COPY . /rag_system/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port to where api call will be made
EXPOSE 8080

# Run app.py when the container launches
CMD ["uvicorn", "rag_system_app:app", "--host", "0.0.0.0", "--port", "8080"]
